TILESET GFX_ASCII_TERM "ascii_n_i.png" NONE NONE
TILESET GFX_ASCII_TERM_SMALL "4x8_by_RKT_v2.png" NONE NONE
TILESET GFX_ASCII_TERM_SMALL_AA "4x8_by_RKT_v2_AA.png" NONE NONE
TILESET GFX_ASCII_MENU "ascii_n_i_menu.png" NONE NONE
TILESET GFX_BGBLOCKS "bg_blocks.png" NONE ALL
#TILESET GFX_ICONS "net.png" BEST NONE
TILESET GFX_ICONS "icons.png" NONE ALL
